version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wx-video-transcoder"
s3_bucket = "wx-video-translation"
s3_prefix = "video-transcoder"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
